In [114]:
import pandas as pd

## Loading the data

In [115]:
A = pd.read_csv(r"C:\Users\admin\Downloads\tmdbdf.csv").head(6000)
A

,Unnamed: 0,index,id,title,overview,keywords,genres,poster_path
0,0,0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","rescue,mission,dream,airplane,paris,france,vir...","Action,ScienceFiction,Adventure",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1,1,1,157336,Interstellar,The adventures of a group of explorers who mak...,"rescue,future,spacecraft,raceagainsttime,artif...","Adventure,Drama,ScienceFiction",/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2,2,2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"joker,sadism,chaos,secretidentity,crimefighter...","Drama,Action,Crime,Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg
3,3,3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","future,society,cultureclash,spacetravel,spacew...","Action,Adventure,Fantasy,ScienceFiction",/kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4,4,4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"newyorkcity,superhero,shield,basedoncomic,alie...","ScienceFiction,Action,Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
...,...,...,...,...,...,...,...,...
5995,5997,5997,508791,The Sun Is Also a Star,Two young New Yorkers begin to fall in love ov...,"newyorkcity,deportation,love,koreanamerican,ba...","Romance,Drama",/pYfI62qgone3Ai0tzgxtQq7chDE.jpg
5996,5998,5998,318256,Hot Girls Wanted,A first-ever look at the realities of the prof...,"pornstar,softcore,craigslist,womandirector,adu...",Documentary,/75ot83QOkc02vujyzmIbumQCU6Y.jpg
5997,5999,5999,314385,By the Sea,"Set in France during the mid-1970s, Vanessa, a...","hotel,france,1970s,sailing,borderlinepersonali...","Drama,Romance",/oEyeG4UyAQvYIJiFpUV57Q3PTDp.jpg
5998,6000,6000,12146,The Missing,When rancher and single mother of two Maggie G...,"daughter,mexico,basedonnovelorbook,newmexico,a...","Thriller,Western,Adventure",/86s5nw5F1G8lJtEowO0LBB4hoBW.jpg
5999,6001,6001,49010,Hobo with a Shotgun,A vigilante homeless man pulls into a new city...,"prostitute,shotgun,dystopia,pimp,vigilante,mas...","Crime,Action,Thriller",/xxMaO7VoN2BnZit79PedVHnTjcO.jpg

## Information about the data

In [116]:
A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   6000 non-null   int64
 1   index        6000 non-null   int64
 2   id           6000 non-null   int64
 3   title        6000 non-null   object
 4   overview     6000 non-null   object
 5   keywords     5860 non-null   object
 6   genres       6000 non-null   object
 7   poster_path  6000 non-null   object
dtypes: int64(3), object(5)
memory usage: 375.1+ KB

In [117]:
A.shape

(6000, 8)

## Missing values

In [118]:
A.isna().sum()

Unnamed: 0       0
index            0
id               0
title            0
overview         0
keywords       140
genres           0
poster_path      0
dtype: int64

## Duplicates

In [119]:
A.duplicated().sum()

np.int64(0)

In [120]:
A.describe(include = object)

,title,overview,keywords,genres,poster_path
count,6000,6000,5860,6000,6000
unique,5850,6000,5830,1538,6000
top,Pinocchio,"Cobb, a skilled thief who commits corporate es...",basedonnovelorbook,Comedy,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
freq,4,1,5,324,1

## Text_Preprocessing

In [121]:
A['tags'] = A['overview'].fillna(' ')+A['keywords'].fillna(' ')+A['genres'].fillna(' ')

In [122]:
A['tags']

0       Cobb, a skilled thief who commits corporate es...
1       The adventures of a group of explorers who mak...
2       Batman raises the stakes in his war on crime. ...
3       In the 22nd century, a paraplegic Marine is di...
4       When an unexpected enemy emerges and threatens...
                              ...
5995    Two young New Yorkers begin to fall in love ov...
5996    A first-ever look at the realities of the prof...
5997    Set in France during the mid-1970s, Vanessa, a...
5998    When rancher and single mother of two Maggie G...
5999    A vigilante homeless man pulls into a new city...
Name: tags, Length: 6000, dtype: object

## Lower

In [123]:
def a(n):
    n = n.lower()
    return n

In [124]:
A['tags'] = A['tags'].apply(a)

In [125]:
A['tags']

0       cobb, a skilled thief who commits corporate es...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime. ...
3       in the 22nd century, a paraplegic marine is di...
4       when an unexpected enemy emerges and threatens...
                              ...
5995    two young new yorkers begin to fall in love ov...
5996    a first-ever look at the realities of the prof...
5997    set in france during the mid-1970s, vanessa, a...
5998    when rancher and single mother of two maggie g...
5999    a vigilante homeless man pulls into a new city...
Name: tags, Length: 6000, dtype: object

## Stemming

In [126]:
from nltk.stem import PorterStemmer

In [127]:
ps = PorterStemmer()

In [128]:
from nltk.stem import WordNetLemmatizer
lemm = WordNetLemmatizer()
lemm.lemmatize('changed')

'changed'

In [129]:
def stemming(n):
    y = []
    for i in n.split():
        y.append(ps.stem(n))
    return  ' '.join(y)

In [130]:
A['tags']

0       cobb, a skilled thief who commits corporate es...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime. ...
3       in the 22nd century, a paraplegic marine is di...
4       when an unexpected enemy emerges and threatens...
                              ...
5995    two young new yorkers begin to fall in love ov...
5996    a first-ever look at the realities of the prof...
5997    set in france during the mid-1970s, vanessa, a...
5998    when rancher and single mother of two maggie g...
5999    a vigilante homeless man pulls into a new city...
Name: tags, Length: 6000, dtype: object

In [131]:
A['tags'] = A['tags'].apply(stemming)

In [132]:
A['tags']

0       cobb, a skilled thief who commits corporate es...
1       the adventures of a group of explorers who mak...
2       batman raises the stakes in his war on crime. ...
3       in the 22nd century, a paraplegic marine is di...
4       when an unexpected enemy emerges and threatens...
                              ...
5995    two young new yorkers begin to fall in love ov...
5996    a first-ever look at the realities of the prof...
5997    set in france during the mid-1970s, vanessa, a...
5998    when rancher and single mother of two maggie g...
5999    a vigilante homeless man pulls into a new city...
Name: tags, Length: 6000, dtype: object

## Vectorization

In [133]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [134]:
tf = TfidfVectorizer(stop_words = 'english',max_features = 21000)

In [135]:
vector = tf.fit_transform(A['tags'])

In [136]:
tf.get_feature_names_out().tolist()

['00',
 '000',
 '007',
 '01',
 '10',
 '100',
 '101',
 '10b',
 '10thcentury',
 '10thcenturyadventure',
 '11',
 '118th',
 '119',
 '11drama',
 '11th',
 '11thcentury',
 '12',
 '120',
 '1200',
 '1215',
 '1250',
 '12th',
 '12thcentury',
 '13',
 '13th',
 '13thcenturyromance',
 '14',
 '140',
 '1453',
 '14th',
 '14thcentury',
 '14thcenturyfantasy',
 '15',
 '150',
 '15th',
 '15thcentury',
 '15thcenturydrama',
 '16',
 '1600s',
 '161',
 '16th',
 '16thcentury',
 '16thcenturyaction',
 '17',
 '1750sadventure',
 '17th',
 '17thcentury',
 '17thcenturydrama',
 '18',
 '180',
 '1800s',
 '1839',
 '1843',
 '1860s',
 '1862',
 '1863',
 '1870s',
 '1874',
 '1890s',
 '1892',
 '1893',
 '18th',
 '18thcentury',
 '19',
 '1900',
 '1900s',
 '1900sdrama',
 '1910s',
 '1913',
 '1917',
 '1918',
 '1920',
 '1920s',
 '1920sdrama',
 '1924',
 '1925',
 '1927',
 '1930s',
 '1930sadventure',
 '1930scomedy',
 '1930scrime',
 '1930sdrama',
 '1931',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1940s',
 '1940saction',
 '1940scomedy',
 '1940sdrama',
 '1940swar',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1949',
 '1950',
 '1950s',
 '1950sadventure',
 '1950sdrama',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1960s',
 '1960saction',
 '1960scomedy',
 '1960scrime',
 '1960sdrama',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1980saction',
 '1980sadventure',
 '1980scomedy',
 '1980scrime',
 '1980sdrama',
 '1980sthriller',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1990s',
 '1990scomedy',
 '1990scrime',
 '1990shorror',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19comedi',
 '19th',
 '19thcentury',
 '19thcenturyadventure',
 '19thcenturyanimation',
 '19thcenturydrama',
 '19thcenturythriller',
 '19thcenturywestern',
 '1stcentury',
 '1stcenturyaction',
 '1stcenturyfamily',
 '1stcenturyhistory',
 '20',
 '200',
 '2000',
 '2000s',
 '2000ssciencefiction',
 '2000swar',
 '2001',
 '2002',
 '2003',
 '2004',
 '2006',
 '2008',
 '2009',
 '2010s',
 '2010scomedy',
 '2011',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2019',
 '2020',
 '2021',
 '2025',
 '2026',
 '2028',
 '2029',
 '2030s',
 '2030saction',
 '2030scomedy',
 '2030scrime',
 '2030ssciencefiction',
 '2035',
 '2040s',
 '2040saction',
 '2040sdrama',
 '2040ssciencefiction',
 '2060s',
 '2070saction',
 '2071',
 '208',
 '20s',
 '20th',
 '20thcentury',
 '21',
 '2159',
 '21st',
 '22',
 '22nd',
 '22ndcentury',
 '23',
 '23rd',
 '23rdcentury',
 '24',
 '2455',
 '24h',
 '24thcenturysciencefiction',
 '25',
 '250',
 '26',
 '27',
 '28',
 '280',
 '28th',
 '29',
 '2ndcentury',
 '30',
 '300',
 '3000',
 '30s',
 '30th',
 '31',
 '34',
 '35',
 '37',
 '39',
 '3danimation',
 '3po',
 '3rdcenturyadventure',
 '40',
 '400',
 '43',
 '45',
 '45th',
 '47',
 '476',
 '49',
 '50',
 '500',
 '50s',
 '50th',
 '51',
 '55',
 '5thcenturybc',
 '60',
 '60s',
 '61',
 '62',
 '643',
 '70',
 '700',
 '70s',
 '72',
 '74th',
 '75',
 '75th',
 '79',
 '80',
 '80s',
 '80sthrowback',
 '86',
 '90s',
 '911',
 '95',
 '96',
 '9thcentury',
 'aaron',
 'aarons',
 'aba',
 'aback',
 'abandon',
 'abandoned',
 'abandonedbaby',
 'abandonedhouse',
 'abandonedmine',
 'abandonedtheater',
 'abandoning',
 'abandonment',
 'abandons',
 'abba',
 'abbey',
 'abbie',
 'abby',
 'abdicates',
 'abduct',
 'abducted',
 'abducting',
 'abduction',
 'abductiondrama',
 'abductions',
 'abducts',
 'abe',
 'abel',
 'abernathy',
 'abiding',
 'abigail',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abode',
 'abolish',
 'abolitionist',
 'abortion',
 'abortionistdrama',
 'abra',
 'abraham',
 'abrahamhistory',
 'abrahamlincoln',
 'abrahams',
 'abrams',
 'abrasive',
 'abroad',
 'abrupt',
 'absence',
 'absent',
 'absolute',
 'absolutely',
 'absorbed',
 'absurd',
 'absurdcomedy',
 'absurdism',
 'absurdity',
 'abudhabicomedy',
 'abuse',
 'abused',
 'abusedwoman',
 'abuseofpower',
 'abuses',
 'abusing',
 'abusive',
 'abusivefather',
 'abusivehusband',
 'abusivemandrama',
 'abusivemarriage',
 'abusivemarriagedrama',
 'abusivemother',
 'abusivemotherdrama',
 'abusiverelationship',
 'aca',
 'academia',
 'academic',
 'academies',
 'academy',
 'acapella',
 'accents',
 'accept',
 'acceptance',
 'acceptancedrama',
 'accepted',
 'accepting',
 'accepts',
 'access',
 'accessories',
 'accident',
 'accidental',
 'accidentaldeath',
 'accidentally',
 'accidentcomedy',
 'accidentdrama',
 'accidentproneadventure',
 'accidents',
 'accidentthril',
 'acclaimed',
 'accolades',
 'accompanied',
 'accompanies',
 'accompany',
 'accompanying',
 'accomplice',
 'accomplices',
 'accomplish',
 'accomplished',
 'accomplishing',
 'according',
 'accordion',
 'account',
 'accountant',
 'accounting',
 'accounts',
 'accuracy',
 'accurate',
 'accursed',
 'accusations',
 'accuse',
 'accused',
 'accusedofmurder',
 'accuses',
 'accusing',
 'accustomed',
 'ace',
 'achieve',
 'achieved',
 'achievements',
 'achieves',
 'aching',
 'acid',
 'acknowledge',
 'acme',
 'acolytes',
 'acorn',
 'acousticguitaradventure',
 'acquaintance',
 'acquaintances',
 'acquainted',
 'acquires',
 'acquitted',
 'acre',
 'acronym',
 'act',
 'acting',
 'action',
 'actionadventureadventure',
 'actionhero',
 'actionheroaction',
 'actionheroadventure',
 'actionherocrime',
 'actionherodrama',
 'actionherosciencefiction',
 'actionherothriller',
 'actions',
 'active',
 'activist',
 'activists',
 'activities',
 'activity',
 'actor',
 'actorplayingthemselfcomedi',
 'actorplayingthemselfcomedy',
 'actorplayingthemselffamily',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'acupuncture',
 'acute',
 'ad',
 'ada',
 'adaline',
 'adam',
 'adams',
 'adapt',
 'adaptation',
 'adapted',
 'adapting',
 'adapts',
 'add',
 'addams',
 'added',
 'addict',
 'addicted',
 'addiction',
 'adding',
 'addison',
 'addition',
 'additional',
 'addled',
 'address',
 'adds',
 'adelaide',
 'adele',
 'adept',
 'adherence',
 'adjective',
 'adjust',
 'adjustment',
 'adler',
 'administered',
 'administration',
 'administrator',
 'admiral',
 'admiration',
 'admired',
 'admiring',
 'admit',
 'admits',
 'admitted',
 'admonition',
 'adolescence',
 'adolescent',
 'adolescents',
 'adolf',
 'adolfhitler',
 'adolfhitlerdrama',
 'adopt',
 'adopted',
 'adoptedchild',
 'adoptedson',
 'adopting',
 'adoption',
 'adoptive',
 'adoptivefather',
 'adoptivemother',
 'adopts',
 'adorable',
 'adorably',
 'adoration',
 'adores',
 'adoring',
 'adoringanimation',
 'adrenaline',
 'adrenalinejunkie',
 'adrian',
 'adriatic',
 'adrift',
 'adult',
 'adultanimation',
 'adultanimationanimation',
 'adultasachild',
 'adulterous',
 'adultery',
 'adulthood',
 'adulthumor',
 'adults',
 'advance',
 'advanced',
 'advancement',
 'advances',
 'advancing',
 'advantage',
 'adventur',
 'adventure',
 'adventurer',
 'adventurers',
 'adventures',
 'adventurous',
 'adversaries',
 'adversary',
 'adverse',
 'advertiser',
 'advertising',
 'advertisingagency',
 'advertisingcampaigndrama',
 'advertisingexecutive',
 'advertisingexpert',
 'advice',
 'advicecolumnist',
 'advise',
 'advised',
 'advisers',
 'advising',
 'advisor',
 'advocate',
 'aerial',
 'aerialcombat',
 'aeronautics',
 'afar',
 'affable',
 'affair',
 'affairs',
 'affect',
 'affected',
 'affection',
 'affectionately',
 'affections',
 'affects',
 'afflicted',
 'affliction',
 'afford',
 'affords',
 'afghan',
 'afghanistan',
 'afghanistanwar',
 'afoul',
 'afraid',
 'africa',
 'african',
 'africanamericanchild',
 'africanamericanhistory',
 'africanamericanhistorydrama',
 'aftercreditsstinger',
 'aftercreditsstingeraction',
 'aftercreditsstingeradventure',
 'aftercreditsstingercomedi',
 'aftercreditsstingercomedy',
 'aftercreditsstingercrime',
 'aftercreditsstingerfamily',
 'aftercreditsstingermystery',
 'afterlife',
 'aftermath',
 'afternoon',
 'againsttheodds',
 'agamemnon',
 'agartha',
 'age',
 'agechangecomedi',
 'agechangefantasy',
 'aged',
 'agedifference',
 'ageing',
 'ageless',
 'agency',
 'agenda',
 'agent',
 'agentadventure',
 'agents',
 'agentsadventure',
 'ageofdiscoveryfamily',
 'ages',
 'aggie',
 'aggression',
 'aggressive',
 'aggressiveintern',
 'aggressively',
 'aggressors',
 'aging',
 'agnes',
 'agnès',
 'ago',
 'agonizes',
 'agoraphobia',
 'agree',
 'agreed',
 'agrees',
 'agu',
 'aguirre',
 'ahead',
 'ahmad',
 'ahsoka',
 'aiads',
 'aibileen',
 'aid',
 'aida',
 'aidan',
 'aide',
 'aided',
 'aiden',
 'aids',
 'ailing',
 'ailment',
 'aim',
 'aimed',
 'aimee',
 'aiming',
 'aimless',
 'aims',
 'air',
 'airbnb',
 'airborne',
 'airbornecar',
 'airconditioner',
 'aircraft',
 'aircraftcarrier',
 'aired',
 'airforce',
 'airforcebase',
 'airforceone',
 'airline',
 'airpirate',
 'airplane',
 'airplaneaccident',
 'airplanecrash',
 'airplanehijacking',
 'airplanepilot',
 'airplanewreck',
 'airport',
 'airportlounge',
 'airship',
 'airspace',
 'airtrafficcontrol',
 'airtrafficcontroller',
 'aisle',
 'aka',
 'akasha',
 'akatsuki',
 'akelarre',
 'aki',
 'akihiko',
 'akira',
 'akiro',
 'al',
 'alabama',
 'aladdin',
 'alain',
 'alan',
 'alarm',
 'alarmclock',
 'alarmed',
 'alarming',
 'alaska',
 'alaskan',
 'albanian',
 'albeit',
 'albert',
 'alberto',
 'albino',
 'album',
 'albums',
 'albus',
 'alcatraz',
 'alcatrazprison',
 'alchemist',
 'alchemistdrama',
 'alchemy',
 'alcohol',
 'alcoholabuse',
 'alcoholic',
 'alcoholicfather',
 'alcoholism',
 'alden',
 'aldo',
 'aldous',
 'alec',
 'alejandro',
 'alert',
 'alex',
 'alexander',
 'alexanderthegreat',
 'alexandra',
 'alexandre',
 'alexia',
 'alexis',
 'alfie',
 'alfonso',
 'alfred',
 'algeria',
 'algerian',
 'algerianwar',
 'algiers',
 'algorithm',
 'algren',
 'ali',
 'alias',
 'alibi',
 'alibicomedi',
 'alice',
 'alicesprings',
 'alicia',
 'alien',
 'alienabduction',
 'alienated',
 'alienattack',
 'aliencontact',
 'aliencreature',
 'aliendnasciencefiction',
 'alienfriendship',
 'alieninfection',
 'alieninfectionhorror',
 'alieninvasion',
 'alieninvasionsciencefiction',
 'alienlanguage',
 'alienlife',
 'alienmonster',
 'alienparasites',
 'alienplanet',
 'alienpossession',
 'alienrace',
 'aliens',
 'alienspacecraft',
 'alienspaceship',
 'alientechnology',
 'align',
 'alike',
 'alisdair',
 'alive',
 'allan',
 'allegations',
 'allegedly',
 'allegiance',
 'allegory',
 'allegra',
 'allen',
 'allergic',
 'allergy',
 'alley',
 'alleys',
 'allgirlband',
 'alliance',
 'alliances',
 'allied',
 'allies',
 'alligator',
 'allison',
 'allow',
 'allowed',
 'allowing',
 'allows',
 'allure',
 'alluring',
 'allworknoplaycomedy',
 'ally',
 'alma',
 'almanac',
 'almightyfantasy',
 'almásy',
 'alongside',
 'aloof',
 'alpaca',
 'alpha',
 'alps',
 'alpsmountains',
 'alqaeda',
 'altar',
 'alter',
 'alteration',
 'altered',
 'alterego',
 'altering',
 'alternate',
 'alternatedimension',
 'alternatehistory',
 'alternatereality',
 'alternatetimeline',
 'alternateuniverseaction',
 'alternative',
 'alternativereality',
 'alternativerealitycomedy',
 'alternativeworld',
 'altman',
 'altmann',
 'altruistic',
 'alva',
 'alvin',
 'alwaystheniceonecomedy',
 'alyosha',
 'alyssa',
 'alzheimer',
 'amaia',
 'amalie',
 'amanda',
 'amateur',
 'amateurdetective',
 'amateurfootball',
 'amato',
 'amazing',
 'amazingly',
 'amazon',
 'amazonrainforest',
 'amazonriver',
 'ambassador',
 'ambassadors',
 'amber',
 'ambiguity',
 'ambiguous',
 'ambiguoushorror',
 'ambition',
 'ambitions',
 'ambitious',
 'ambivalent',
 'ambulance',
 'ambush',
 'ambushed',
 'ambushes',
 'amelia',
 'ameliorate',
 'amends',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americancivilwaraction',
 'americancountrysidehorror',
 'americanculture',
 'americandream',
 'americandreamfantasy',
 'americanembassy',
 'americanexpress',
 'americanfootball',
 'americanfootballcoach',
 'americangiallocrime',
 'americanhistorydrama',
 'americans',
 'americanspy',
 'americanspycomedy',
 'americanwayoflife',
 'americanwest',
 'americanwilderness',
 'amiable',
 'amiably',
 'amid',
 'amidst',
 'amish',
 'amistad',
 'amity',
 'amityville',
 'amityvillehorrorthriller',
 'amnesia',
 'amnesiac',
 'amok',
 'amoral',
 'amp',
 'amplified',
 'amplifiermusic',
 'amputation',
 'amsterdam',
 'amulet',
 'amundsen',
 'amused',
 'amusedaction',
 'amusement',
 'amusementpark',
 'amusphere',
 'amy',
 'ana',
 'anaconda',
 'anacondas',
 'anakin',
 'analog',
 'analogue',
 'analysis',
 'analyst',
 'anarchiccomedy',
 'anarchiccomedycomedi',
 'anarchiccomedycomedy',
 'anarchist',
 'anarchy',
 'anastasia',
 'ancestor',
 'ancestry',
 'anchor',
 'anchorman',
 'ancient',
 'ancientcivilization',
 'ancientegypt',
 'ancientegyptfamily',
 'ancientevil',
 'ancientgreece',
 'ancientlanguagefilmaction',
 'ancientrome',
 'ancientwarfare',
 'ancientworld',
 'andalasia',
 'anderson',
 'anderton',
 'andesmountains',
 'andie',
 'andrea',
 'andrei',
 'andrew',
 'andrews',
 'androgyny',
 'android',
 'androids',
 'andré',
 'andy',
 'anesthesia',
 'anesthetic',
 'angel',
 'angela',
 'angelenos',
 'angeles',
 'angelic',
 'angellier',
 'angelofdeath',
 'angelov',
 'angels',
 'anger',
 'angerissuescomedi',
 'angermanagement',
 'angers',
 'angie',
 'angry',
 'angrymob',
 'angst',
 'anim',
 'animal',
 'animalaction',
 'animaladventure',
 'animalattack',
 'animalcruelty',
 'animalfamily',
 'animalhorror',
 'animalhorroraction',
 'animalhorrorfantasy',
 'animalhorrorhorror',
 'animalkilling',
 'animallead',
 ...]

## Caluculate the Similarity

In [137]:
from sklearn.metrics.pairwise import cosine_similarity

In [138]:
similarity = cosine_similarity(vector)

In [139]:
similarity1 = pd.DataFrame(similarity,index = A['title'],columns = A['title'])
similarity1

title,Inception,Interstellar,The Dark Knight,Avatar,The Avengers,Deadpool,Avengers: Infinity War,Fight Club,Guardians of the Galaxy,Pulp Fiction,...,Grace of Monaco,The Gendarme and the Creatures from Outer Space,Barbie: The Princess & The Popstar,Polytechnique,Open Season 3,The Sun Is Also a Star,Hot Girls Wanted,By the Sea,The Missing,Hobo with a Shotgun
title,,,,,,,,,,,,,,,,,,,,,
Inception,1.000000,0.028961,0.000000,0.011467,0.023323,0.004977,0.000000,0.000000,0.052056,0.021435,...,0.011802,0.009918,0.005023,0.000000,0.000000,0.006037,0.011751,0.021386,0.010028,0.000000
Interstellar,0.028961,1.000000,0.000000,0.063328,0.000000,0.000000,0.040927,0.015686,0.054315,0.023886,...,0.003315,0.006571,0.000000,0.003403,0.004758,0.003766,0.000000,0.024331,0.000000,0.021410
The Dark Knight,0.000000,0.000000,1.000000,0.000000,0.039756,0.036186,0.030740,0.000000,0.018268,0.024120,...,0.000000,0.026829,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.026574,0.073604
Avatar,0.011467,0.063328,0.000000,1.000000,0.000000,0.006802,0.021426,0.000000,0.021044,0.000000,...,0.000000,0.033019,0.000000,0.000000,0.004698,0.000000,0.000000,0.000000,0.000000,0.009071
The Avengers,0.023323,0.000000,0.039756,0.000000,1.000000,0.039637,0.089718,0.000000,0.169217,0.000000,...,0.000000,0.027800,0.000000,0.000000,0.008547,0.012351,0.009840,0.000000,0.011451,0.012675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
The Sun Is Also a Star,0.006037,0.003766,0.000000,0.000000,0.012351,0.012922,0.005623,0.006281,0.000000,0.000000,...,0.004819,0.000000,0.006298,0.004947,0.021406,1.000000,0.000000,0.018533,0.017636,0.005125
Hot Girls Wanted,0.011751,0.000000,0.000000,0.000000,0.009840,0.000000,0.007496,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.036305,0.000000,1.000000,0.016020,0.000000,0.000000
By the Sea,0.021386,0.024331,0.000000,0.000000,0.000000,0.000000,0.000000,0.009363,0.000000,0.000000,...,0.023606,0.019838,0.000000,0.000000,0.000000,0.018533,0.016020,1.000000,0.000000,0.000000
The Missing,0.010028,0.000000,0.026574,0.000000,0.011451,0.000000,0.000000,0.013513,0.013387,0.000000,...,0.000000,0.008164,0.000000,0.000000,0.000000,0.017636,0.000000,0.000000,1.000000,0.019951
Hobo with a Shotgun,0.000000,0.021410,0.073604,0.009071,0.012675,0.027726,0.007918,0.019422,0.014818,0.018342,...,0.000000,0.025446,0.008785,0.040654,0.002918,0.005125,0.000000,0.000000,0.019951,1.000000

In [141]:
import numpy as np

def recommend(movie):
    idx = A[A['title'] == movie].index[0]
    movie_list = np.argsort(similarity1.iloc[idx][::-1][1:6])
    return A.iloc[movie_list].title.tolist()

In [142]:
recommend('Interstellar')

['Inception', 'The Dark Knight', 'Avatar', 'The Avengers', 'Interstellar']

In [143]:
A['poster_path']

0       /oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1       /gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2       /qJ2tW6WMUDux911r6m7haRef0WH.jpg
3       /kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4        /RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
                      ...
5995    /pYfI62qgone3Ai0tzgxtQq7chDE.jpg
5996    /75ot83QOkc02vujyzmIbumQCU6Y.jpg
5997    /oEyeG4UyAQvYIJiFpUV57Q3PTDp.jpg
5998    /86s5nw5F1G8lJtEowO0LBB4hoBW.jpg
5999    /xxMaO7VoN2BnZit79PedVHnTjcO.jpg
Name: poster_path, Length: 6000, dtype: object

In [144]:
base_url = 'https://image.tmdb.org/t/p/w500/'
print(base_url+'/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg')

https://image.tmdb.org/t/p/w500//gEU2QniE6E77NI6lCU6MxlNBvIx.jpg

In [145]:
A[A['title'] == 'Interstellar']['poster_path']

1    /gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
Name: poster_path, dtype: object

## Pickle File`

In [146]:
import pickle

In [147]:
with open(r'F:\Recommendation_sstem\similarity.pkl','wb') as f:
    pickle.dump(similarity,f)